# .streamlit/config.toml
[server]
port = 8502
address = "0.0.0.0"
baseUrlPath = "/minutes"
enableCORS = false
headless = true
# ファイルアップロードの上限解除
maxUploadSize = 1024


# 開発環境 (自分だけで使う場合)
# [server]
# port = 8502
# address = "localhost"
# headless = false

# 社内LAN / サーバー環境 (他のPCからもアクセスする場合)
# [server]
# port = 8502
# address = "0.0.0.0"
# baseUrlPath = "/minutes"
# headless = true
